<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Device;
use Illuminate\Http\Request;

class DeviceController extends Controller
{
    public function sync(Request $request)
    {
        $request->validate([
            'fcm_token'   => 'required|string',
            'device_uuid' => 'required|string', // Unique ID generated by the phone
            'platform'    => 'nullable|string|in:android,ios',
            'language'    => 'nullable|string|max:10',
            'app_version' => 'nullable|string',
        ]);

        $user = $request->user();

        // Update existing device or create new one based on UUID
        // We update 'app_user_id' to ensure this device is now linked to the CURRENT user
        $device = Device::updateOrCreate(
            ['device_uuid' => $request->device_uuid],
            [
                'app_user_id' => $user->id,
                'fcm_token'   => $request->fcm_token,
                'platform'    => $request->platform,
                'language'    => $request->language,
                'app_version' => $request->app_version,
            ]
        );

        return response()->json([
            'status' => 'success',
            'message' => 'Device synced successfully'
        ]);
    }
}